
## application informations
info:
  app:
    name: immoblier service application
    description: Microservice IMO-SERVICE
    version: 1.0.0

server:
  port: 1010
  servlet:
    context-path: /imo-api
 

## h2 settings
spring:
  datasource:
    url: jdbc:h2:./database/samspledb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      format_sql: 'true'
      ddl-auto: create-drop
    show-sql: 'true'
 
